Get started
tsparticles/storybook pull request #3
Opened 2022-10-24 16:12 UTC by Enhmunh-E

As this is a Storybook project there is no need to start the project by yarn start. So I think newcomers won't understand how to start the project.
Added a readme.md

2022-10-24 16:20 UTC, matteobruni requested changes

2022-10-24 16:20 UTC, matteobruni commented on docs/README.md
> +# Storybook for TSParticles
tsParticles instead of TSParticles

2022-10-24 16:20 UTC, matteobruni commented on docs/README.md
> +1. `yarn install` at project root level
`yarn` is enough

2022-10-24 16:20 UTC, matteobruni commented on docs/README.md
> +Contact: matteobruni
Instead of contact information, use the main website: https://particles.js.org

2022-10-25 07:06 UTC, matteobruni approved these changes

2022-10-25 07:06 UTC, merged

2022-10-25 09:15 UTC, Enhmunh-E commented
can you add hacktoberfest label, please? @matteobruni